version: 2.1
jobs:
  build:
    machine:
      # https://circleci.com/docs/configuration-reference#available-linux-machine-images
      image: ubuntu-2204:2022.07.1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Open Xserver connections
          command: 'xhost +local:'
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install build-essential
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            brew install dive hadolint
            curl -fsSL https://goss.rocks/install | sudo sh
      - run:
          name: Build the image
          command: make build-ci
      - run:
          name: Lint
          command: |
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            make lint
      - run:
          name: Goss tests
          command: |
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            make test
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large

workflows:
  version: 2
  test:
    jobs:
      - build
