version: 2.1
jobs:
  build:
    # https://circleci.com/docs/configuration-reference/#available-linux-machine-images-cloud
    machine:
      image: ubuntu-2204:2023.10.1
    # https://circleci.com/docs/2.0/configuration-reference/#resourceclass
    resource_class: large
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Open Xserver connections
          command: 'xhost +local:'
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install build-essential
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            brew install dive hadolint
            curl -fsSL https://goss.rocks/install | sudo sh
      - run:
          name: Build the image
          command: make build-ci
      - run:
          name: Lint
          command: |
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            make lint
      - run:
          name: Goss tests
          command: |
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            make test

workflows:
  version: 2
  test:
    jobs:
      - build
