version: 2.1
jobs:
  build:
    machine:
      # https://circleci.com/docs/2.0/configuration-reference/#available-machine-images
      image: ubuntu-2004:202104-01
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Open Xserver connections
          command: 'xhost +local:'
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install build-essential
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            brew update
            brew install dive
            curl -fsSL https://goss.rocks/install | sudo sh
      - run:
          name: Build the image
          command: make build-ci
      - run:
          name: Lint
          command: make lint
      - run:
          name: Goss tests
          command: |
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            make test

workflows:
  version: 2
  test:
    jobs:
      - build
