name: CI

on:
  pull_request:
    branches:
      - main

env:
  TAG: githubci

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@1623ba61710b974b55ba455930e6f2c8ef919778 # v1.3.1
