name: CI

on:
  pull_request:
    branches:
      - main

env:
  TAG: githubci

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
