name: CI

on:
  pull_request:
    branches:
      - main

env:
  TAG: githubci

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@v1.4.0
