name: Deploy Docker Image

on:
  release:
    types:
      - published

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Deploy the Docker image to GitHub Container Registry - Semver
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/pgmodeler
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_PAT }}
        registry: ghcr.io
        tag_semver: true

    - name: Deploy the Docker image to GitHub Container Registry - Latest
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/pgmodeler
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_PAT }}
        registry: ghcr.io
        tags: "latest"

    - name: Deploy the Docker image to Docker Hub - Semver
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/pgmodeler
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
        tag_semver: true
    
    - name: Deploy the Docker image to Docker Hub - Latest
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: artis3n/pgmodeler
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
        tags: "latest"
