name: Deploy Docker Image

on:
  release:
    types:
      - published

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.3.0

    - name: Cache Docker layers
      uses: actions/cache@v2.1.5
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.REGISTRY_PAT }}

    - name: Docker meta
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v2.3.0
      with:
        images: ghcr.io/artis3n/pgmodeler-container
        tag-latest: true
        tag-sha: true
        tag-semver: |
          {{version}}
          {{major}}.{{minor}}
          {{major}}

    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        context: .
        file: ./Dockerfile
        build-args: |
          --progress plain
        tags: ${{ steps.docker_meta.outputs.tags }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
      env:
        DOCKER_BUILDKIT: 1
