name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  TAG: githubci

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Install dependencies
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
          brew install dive
          curl -fsSL https://goss.rocks/install | sh

      - name: Build image
        run: make build
      
      - name: Test the image
        run: make test
